<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                "name" => "chair1",
                "desc" => "wow what a chair lol",
                "stock" => 10,
                "price" => 149,
                "image" => "product_1.png",
                "category" => "chair",
                "user_id" => 1,
            ],
            [
                "name" => "chair2",
                "desc" => "wow what a chair lol",
                "stock" => 20,
                "price" => 249,
                "image" => "product_2.png",
                "category" => "chair",
                "user_id" => 1,
            ],
            [
                "name" => "chair3",
                "desc" => "wow what a chair lol",
                "stock" => 30,
                "price" => 349,
                "image" => "product_3.png",
                "category" => "chair",
                "user_id" => 1,
            ],
            [
                "name" => "chair4",
                "desc" => "wow what a chair lol",
                "stock" => 40,
                "price" => 449,
                "image" => "product_4.png",
                "category" => "chair",
                "user_id" => 1,
            ],
            [
                "name" => "chair5",
                "desc" => "wow what a chair lol",
                "stock" => 50,
                "price" => 549,
                "image" => "product_5.png",
                "category" => "chair",
                "user_id" => 1,
            ],
            [
                "name" => "chair6",
                "desc" => "wow what a chair lol",
                "stock" => 60,
                "price" => 649,
                "image" => "product_6.png",
                "category" => "chair",
                "user_id" => 1,
            ],
            [
                "name" => "chair7",
                "desc" => "wow what a chair lol",
                "stock" => 70,
                "price" => 749,
                "image" => "product_7.png",
                "category" => "chair",
                "user_id" => 1,
            ],
            [
                "name" => "chair8",
                "desc" => "wow what a chair lol",
                "stock" => 80,
                "price" => 849,
                "image" => "product_8.png",
                "category" => "chair",
                "user_id" => 1,
            ],

            [
                "name" => "inspired1",
                "desc" => "wow what a description",
                "stock" => 10,
                "price" => 111,
                "image" => "i1.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "inspired2",
                "desc" => "wow what a description",
                "stock" => 20,
                "price" => 222,
                "image" => "i2.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "inspired3",
                "desc" => "wow what a description",
                "stock" => 30,
                "price" => 311,
                "image" => "i3.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "inspired4",
                "desc" => "wow what a description",
                "stock" => 40,
                "price" => 411,
                "image" => "i4.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "inspired5",
                "desc" => "wow what a description",
                "stock" => 50,
                "price" => 511,
                "image" => "i5.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "inspired6",
                "desc" => "wow what a description",
                "stock" => 60,
                "price" => 611,
                "image" => "i6.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "inspired7",
                "desc" => "wow what a description",
                "stock" => 70,
                "price" => 711,
                "image" => "i7.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "inspired8",
                "desc" => "wow what a description",
                "stock" => 80,
                "price" => 811,
                "image" => "i8.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],

            [
                "name" => "model1",
                "desc" => "wow what a description about model",
                "stock" => 10,
                "price" => 123,
                "image" => "i1.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "model2",
                "desc" => "wow what a description about model",
                "stock" => 20,
                "price" => 223,
                "image" => "i2.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "model3",
                "desc" => "wow what a description about model",
                "stock" => 30,
                "price" => 323,
                "image" => "i3.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "model4",
                "desc" => "wow what a description about model",
                "stock" => 40,
                "price" => 423,
                "image" => "i4.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "model5",
                "desc" => "wow what a description about model",
                "stock" => 50,
                "price" => 523,
                "image" => "i5.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "model6",
                "desc" => "wow what a description about model",
                "stock" => 60,
                "price" => 623,
                "image" => "i6.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "model7",
                "desc" => "wow what a description about model",
                "stock" => 70,
                "price" => 723,
                "image" => "i7.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
            [
                "name" => "model8",
                "desc" => "wow what a description about model",
                "stock" => 80,
                "price" => 823,
                "image" => "i8.jpg",
                "category" => "inspired",
                "user_id" => 1,
            ],
        ]);
    }
}
