<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                "name" => "chair1",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "product_1.png",
                "category_id" => 1,
                "user_id" => 1,
            ],
            [
                "name" => "chair2",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "product_2.png",
                "category_id" => 1,
                "user_id" => 1,
            ],
            [
                "name" => "chair3",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "product_3.png",
                "category_id" => 1,
                "user_id" => 1,
            ],
            [
                "name" => "chair4",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "product_4.png",
                "category_id" => 1,
                "user_id" => 1,
            ],
            [
                "name" => "chair5",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "product_5.png",
                "category_id" => 1,
                "user_id" => 1,
            ],
            [
                "name" => "chair6",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "product_6.png",
                "category_id" => 1,
                "user_id" => 1,
            ],
            [
                "name" => "chair7",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "product_7.png",
                "category_id" => 1,
                "user_id" => 1,
            ],
            [
                "name" => "chair8",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "product_8.png",
                "category_id" => 1,
                "user_id" => 1,
            ],

            [
                "name" => "inspired1",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "i1.jpg",
                "category_id" => 2,
                "user_id" => 1,
            ],
            [
                "name" => "inspired2",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "i2.jpg",
                "category_id" => 2,
                "user_id" => 1,
            ],
            [
                "name" => "inspired3",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "i3.jpg",
                "category_id" => 2,
                "user_id" => 1,
            ],
            [
                "name" => "inspired4",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "i4.jpg",
                "category_id" => 2,
                "user_id" => 1,
            ],
            [
                "name" => "inspired5",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "i5.jpg",
                "category_id" => 2,
                "user_id" => 1,
            ],
            [
                "name" => "inspired6",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "i6.jpg",
                "category_id" => 2,
                "user_id" => 1,
            ],
            [
                "name" => "inspired7",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "i7.jpg",
                "category_id" => 2,
                "user_id" => 1,
            ],
            [
                "name" => "inspired8",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "i8.jpg",
                "category_id" => 2,
                "user_id" => 1,
            ],

            [
                "name" => "model1",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "model1.jpg",
                "category_id" => 3,
                "user_id" => 1,
            ],
            [
                "name" => "model2",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "model2.jpg",
                "category_id" => 3,
                "user_id" => 1,
            ],
            [
                "name" => "model3",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "model3.jpg",
                "category_id" => 3,
                "user_id" => 1,
            ],
            [
                "name" => "model4",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "model4.jpg",
                "category_id" => 3,
                "user_id" => 1,
            ],
            [
                "name" => "model5",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "model5.jpg",
                "category_id" => 3,
                "user_id" => 1,
            ],
            [
                "name" => "model6",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "model6.jpg",
                "category_id" => 3,
                "user_id" => 1,
            ],
            [
                "name" => "model7",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "model7.jpg",
                "category_id" => 3,
                "user_id" => 1,
            ],
            [
                "name" => "model8",
                "desc" => fake()->sentence(10),
                "stock" => fake()->numberBetween(3, 15),
                "price" => fake()->numberBetween(99, 399),
                "image" => "model8.jpg",
                "category_id" => 3,
                "user_id" => 1,
            ],
        ]);
    }
}
